# Generated by Django 4.1.4 on 2022-12-23 05:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0006_modely'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodel',
            name='update_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
